spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Logs detalhados da conexão
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator=DEBUG

spring.jpa.hibernate.ddl-auto=update