spring.datasource.url=jdbc:postgresql://postgress_19o1_user:lghE9QW4m2JxtYu4w87OEfhM8CulMnO7@dpg-d9n9nsajnfac73alj16g-a.oregon-postgres.render.com/postgress_19o1
spring.datasource.password=lghE9QW4m2JxtYu4w87OEfhM8CulMnO7
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update